name: Publish a new release

on:
  push:
    branches:
    - fix/semantic-trigger

jobs:
  release:
    name: Semantic-Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: yarn install
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          "semantic-release-config-gitmoji"
        extends: semantic-release-config-gitmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
